
NEWLINE = '_NEWLINE_'

ORDER = "ORDER"
SENTENCE = "SENTENCE"
ORDER_IN_SENTENCE = "ORDER_IN_SENTENCE"
ORTH = "ORTH"
LOWER = "LOWER"
POS = "POS"
LEMMA = "LEMMA"
STEM = "STEM"
IS_PUNCT = "IS_PUNCT"
IS_STOP = "IS_STOP"
IS_NUM = "IS_NUM"
IS_ALPHA = "IS_ALPHA"
HYPERNYM = "HYPERNYM"
SYNONYM = "SYNONYM"
ANTONYM = "ANTONYM"